### PR TITLE
Use GitHub Actions

### PR DESCRIPTION
**Pull request by krlmlr**
The Travis workflow contains a script that pushes to xran, still need to migrate that.

### CODE REVIEW

**Comment by cderv** [comment]
I don't think it worth keeping the publishing to xran. We did not kept that for other workflows that did it when we switched from Travis to GHA, mainly thanks to r-universe which offers the same now. So installing the binary from https://r-lib.r-universe.dev/ would work as it was from XRAN. cc @yihui

**Review by yihui — COMMENTED** [review]
I'd like to delete `.travis.yml` and merge `.github/workflows/R-CMD-check.yaml` first. For the rest of workflows, we can add them when we actually need them. Thanks!

**Comment by krlmlr** [comment]
Do you want coverage tests on GitHub Actions?

**Comment by yihui** [comment]
I'm okay with the coverage workflow. Thanks!

**Pull request merged**
